const express = require("express");
const path = require("path");
const app = express();
app.use(express.static(__dirname));
app.listen(process.env.PORT||3000,function(){console.log("ok");});
app.get("/ping",function(req,res){res.json({ok:true});});
app.get("/status",function(req,res){res.json({botRunning:false,paper:true,equity:0,cash:0,dailyPnL:0,positions:[]});});
app.all("/bot/start",function(req,res){res.json({ok:true,botRunning:true});});
app.all("/bot/stop",function(req,res){res.json({ok:true,botRunning:false});});
app.get("/trades",function(req,res){res.json({trades:[]});});
app.get("/signals",function(req,res){res.json({signals:[]});});
app.get("/prices",function(req,res){res.json({prices:{}});});
app.get("/",function(req,res){res.sendFile(path.join(__dirname,"index.html"));});
